<div class="container">
  <fieldset>
    <h2>Cadastro de Contatos</h2>
    <div class="container text-center">
      <div class="row align-items-start">
        <div class="col" name="col1">
          <form method="post" action="/salvar-pessoa">
            <?php if (!isset($pessoa)) : ?>
              <div class="input-group mb-3" style="width:40%">
                <span class="input-group-text" id="inputGroup-sizing-default">Nome:</span>
                <input id="nome" name="nome" type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
              </div>
            <?php endif ?>
            <!-- </form> -->

            <?php if ($pessoa) : ?>
              <!-- <form method="post" action="/pessoa/cadastrarPessoa/saveContato"> -->
              <div class="form-floating mb-3" style="width:95%">
                <input type="text" class="form-control" id="atualNome" placeholder="name@example.com" disabled>
                <label for="atualNome"><?= $pessoa->nome ?></label>
                <input type="hidden" name="id" id="id" value="<?= $pessoa->id ?>">
              </div>
              <div class="input-group mb-3" style="width:95%">
                <span class="input-group-text" id="inputGroup-sizing-default">Novo nome:</span>
                <input id="nome" name="nome" type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
              </div>
            <?php endif ?>
            <button type="submit" class='btn btn-dark'>
              Salvar
            </button>
          </form>
          <?php if (isset($pessoa->id)) : ?>
            <form method="post" action="/salvar-contato">
              <div style="padding-top:10px; width:95%">
                <div class="form-floating mb-3">
                  <input type="text" class="form-control" id="tipoContato" name="tipoContato" placeholder="Email, Telefone, Whatsapp">
                  <label for="tipoContato">Tipo contato(telefone, e-mail, whatsapp, etc.)</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="text" class="form-control" id="descrContato" name="descrContato" placeholder="name@example.com, 62 9999-9999">
                  <label for="descrContato">Contato</label>
                </div>
                <input type="hidden" name="id_pessoa" value="<?= $pessoa->id ?>">
                <button class="btn btn-outline-secondary" type="submit">Adicionar Contato</button>
              </div>
            </form>
          <?php endif ?>
        </div>
        <div class="col" name="col2">
          <?php if (count($pessoa->contatos) > 0) : ?>
            <div>
              <table class="table table-hover">
                <tr>
                  <th>
                    Tipo Contato
                  </th>
                  <th>
                    Contato
                  </th>
                </tr>
                <?php foreach ($pessoa->contatos as $item) : ?>
                  <tr>
                    <td>
                      <?= $item->tipo ?>
                    </td>
                    <td>
                      <?= $item->descricao ?>
                    </td>
                    <td>
                        <a class='btn btn-danger' href="/excluir-contato/<?= $item->id ?>/<?= $item->id_pessoa ?>">
                          Remover Contato
                        </a>
                    </td>
                  </tr>
                <?php endforeach ?>
              </table>
            </div>
          <?php endif ?>
        </div>
      </div>
    </div>

  </fieldset>
</div>