<div class="container">
  <h1>Contatos</h1>
  <button onclick='location.href="/cadastrar-pessoa"' class='btn btn-dark'>
    Novo Cadastro
  </button>
  <table class="table table-hover">
    <tr>
      <th>
        Codigo
      </th>
      <th>
        Nome
      </th>
    </tr>
    <?php foreach ($pessoas as $item) : ?>
      <tr>
        <td>
          <?= $item->id ?>
        </td>
        <td>
          <?= $item->nome ?>
        </td>
        <td>
          <a class='btn btn-dark' href="cadastrar-pessoa?id=<?= $item->id ?>">
            Editar/Detalhes
          </a>
        </td>
        <td>
          <a href="/excluir-pessoa/<?= $item->id ?>" class='btn btn-danger'>
            Excluir
          </a>
        </td>
      </tr>
    <?php endforeach ?>

    <?php if (count($pessoas) == 0) : ?>
      <tr>
        <td colspan="5">Nenhum registro encontrado.</td>
      </tr>
    <?php endif ?>

  </table>

</div>