<!doctype html>
<html lang="pt-br">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Agenda de Contatos</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #e3f2fd;">
        <div class="container-fluid">
            <a class="navbar-brand" href="/listar-contatos">
                Agenda
            </a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/listar-contatos">Listar Cadastros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/suportes-balanceados">Suportes Balanceados</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <?php

use Controller\PessoaController;

    $url = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);

    switch ($url) {
        case '/':
            echo "Página inicial";
            break;

        case '/listar-contatos':
            include 'views/ListarContato.phtml';
            break;

        case '/cadastrar-pessoa':
            include 'views/CadastrarContato.phtml';
            break;

        /* case '/pessoa/cadastrarPessoa/save':
            if ($_SERVER['REQUEST_METHOD'] === 'POST') {
                PessoaController::savePessoa();
            } else {
                header("Location: {$baseUrl}");
                exit();
            }
            break;

        case '/pessoa/delete':
            PessoaController::deletePessoa();
            break;

        case '/pessoa/cadastrarPessoa/cadastrarContato/save':
            if ($_SERVER['REQUEST_METHOD'] === 'POST') {
                PessoaController::salvarContato();
            } else {
                header("Location: {$baseUrl}");
                exit();
            }
            break;

        case '/pessoa/excluirContato':
            PessoaController::deleteContato();
            break;
 */
        default:
            echo "Erro 404";
            break;
    }
 ?>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>